image: node:22

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

options:
  size: 2x

definitions:
  caches:
    sonar: ~/.sonar/cache
  services:
    docker:
      memory: 4096
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - sonar
        services:
          - docker
        script:
          - yarn install
          - yarn dedupe
          - yarn build
          - pipe: sonarsource/sonarcloud-scan:2.0.0
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}

pipelines:                 # More info here: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
  branches:
    '**':
      - step: *build-test-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
