export const moyenneInitialValues = {
  capaciteMoyenne: 0,
  realisationAcitiviteMoyenne: 0,
  fileActivePersonnesAccompagnesMoyenne: 0,
  hebergementPermanentMoyenne: 0,
  hebergementTemporaireMoyenne: 0,
  acceuilDeJourMoyenne: 0,
  prestationExterneMoyenne: 0,
  rotationPersonnelMoyenne: 0,
  etpVacantMoyenne: 0,
  absenteismeMoyenne: 0,
  tauxCafMoyenne: 0,
  vetusteConstructionMoyenne: 0,
  roulementNetGlobalMoyenne: 0,
  resultatNetComptableMoyenne: 0,
};
