import { UtilisateurModel } from "../../../../../database/models/UtilisateurModel";

export const tableData = [
  {
    id: 1,
    userId: "",
    annee: 2023,
    capacite_totale: "127",
    realisation_activite: "100,1",
    numéroFiness: "010008407",
    socialReason: "CH DU HAUT BUGEY",
    type: "Entités Juridiques",
    user: new UtilisateurModel(),
    hp: "22 %",
    ht: "18 %",
    aj: "60 %",
    prestations_externes_vs_direct: "18 %",
    rotation_personnel: "5 %",
    ETP_vacants: "0 %",
    abesenteisme: "4.6 %",
    CAF: "5.9 %",
    vetuste: "45.2 %",
    resultat_net_comptable: "-115 646 €",
  },
  {
    id: 2,
    userId: "",
    annee: 2023,
    capacite_totale: "121",
    realisation_activite: "87.8",
    numéroFiness: "010003598",
    socialReason: "IFAS CH DU HAUT BUGEY",
    type: "Social et Médico-social",
    user: new UtilisateurModel(),
    hp: "22 %",
    ht: "18 %",
    aj: "60 %",
    prestations_externes_vs_direct: "18 %",
    rotation_personnel: "5 %",
    ETP_vacants: "0 %",
    abesenteisme: "4.6 %",
    CAF: "5.9 %",
    vetuste: "45.2 %",
    resultat_net_comptable: "-115 646 €",
  },
  {
    id: 3,
    userId: "",
    annee: 2022,
    capacite_totale: "121",
    realisation_activite: "87.8",
    numéroFiness: "010005239",
    socialReason: "CH DU HAUT BUGEY - GEOVREISSET",
    type: "Sanitaire",
    user: new UtilisateurModel(),
    hp: "22 %",
    ht: "18 %",
    aj: "60 %",
    prestations_externes_vs_direct: "18 %",
    rotation_personnel: "5 %",
    ETP_vacants: "0 %",
    abesenteisme: "4.6 %",
    CAF: "5.9 %",
    vetuste: "45.2 %",
    resultat_net_comptable: "-115 646 €",
  },
  {
    id: 4,
    userId: "",
    annee: 2021,
    capacite_totale: "84",
    realisation_activite: "87.8",
    numéroFiness: "010007961",
    socialReason: "SSIAD CH HAUT-BUGEY SITE DE NANTUA",
    type: "Social et Médico-social",
    user: new UtilisateurModel(),
    hp: "22 %",
    ht: "18 %",
    aj: "60 %",
    prestations_externes_vs_direct: "18 %",
    rotation_personnel: "5 %",
    ETP_vacants: "0 %",
    abesenteisme: "4.6 %",
    CAF: "5.9 %",
    vetuste: "45.2 %",
    resultat_net_comptable: "-115 646 €",
  },
  {
    id: 5,
    userId: "",
    annee: 2021,
    capacite_totale: "84",
    realisation_activite: "87.8",
    numéroFiness: "010786036",
    socialReason: 'EHPAD 84 "LES JARDINS DU LAC"',
    type: "Social et Médico-social",
    user: new UtilisateurModel(),
    hp: "22 %",
    ht: "18 %",
    aj: "60 %",
    prestations_externes_vs_direct: "18 %",
    rotation_personnel: "5 %",
    ETP_vacants: "0 %",
    abesenteisme: "4.6 %",
    CAF: "5.9 %",
    vetuste: "45.2 %",
    resultat_net_comptable: "-115 646 €",
  },
  {
    id: 6,
    userId: "",
    annee: 2023,
    capacite_totale: "121",
    realisation_activite: "87.8",
    numéroFiness: "010786077",
    socialReason: "EHPAD LE TOURNANT DES SAISONS",
    type: "Social et Médico-social",
    user: new UtilisateurModel(),
    hp: "22 %",
    ht: "18 %",
    aj: "60 %",
    prestations_externes_vs_direct: "18 %",
    rotation_personnel: "5 %",
    ETP_vacants: "0 %",
    abesenteisme: "4.6 %",
    CAF: "5.9 %",
    vetuste: "45.2 %",
    resultat_net_comptable: "-115 646 €",
  },
];
