export type ÉtablissementTerritorialIdentité = Readonly<{
  catégorieAgrégatÉtablissement: string
  catégorieÉtablissement: string
  codeApe: string
  codeMft: string
  codePays: string
  codePostal: string
  codeSph: string
  commune: string
  complémentDistribution: string
  complémentRaisonSociale: string
  complémentVoie: string
  courriel: string
  dateAutorisation: string
  dateCaducité: string
  dateFermeture: string
  dateMaj: string
  dateMiseAJourSource: string
  dateModificationSiret: string
  dateOuverture: string
  département: string
  indicateurCaducité: string
  libelléCatégorieAgrégatÉtablissement: string
  libelléCatégorieÉtablissement: string
  libelléCommune: string
  libelléCourtCatégorieAgrégatÉtablissement: string
  libelléCourtCatégorieÉtablissement: string
  libelléCourtMft: string
  libelléCourtSph: string
  libelléDépartement: string
  libelléMft: string
  libelléPays: string
  libelléSph: string
  lieuDitBoîtePostale: string
  ligneAcheminement: string
  natureÉtablissement: string
  numéroFinessEntitéJuridique: string
  numéroFinessÉtablissementPrincipal: string
  numéroFinessÉtablissementTerritorial: string
  numéroVoie: string
  numéroÉducationNationale: string
  origineModificationSiret: string
  raisonSociale: string
  raisonSocialeLongue: string
  siret: string
  typeFermeture: string
  typeVoie: string
  typeÉtablissement: string
  télécopie: string
  téléphone: string
  voie: string
}>
