#!/bin/bash

COMMIT_MSG_FILE=$1

if [[ -d ".git/rebase-merge" ]]; then
  exit 0
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
COMMIT_MSG="$(cat $COMMIT_MSG_FILE)"

if [ -n "$BRANCH_NAME" ] && grep --quiet --regexp "^hel-[0-9]*/.*" <<< $BRANCH_NAME && ! grep --quiet --regexp "^(hel-[0-9]*).*" <<< $COMMIT_MSG; then
  TICKET="${BRANCH_NAME%/*}"

  sed -i.bak -e "1s/^/($TICKET) /" $COMMIT_MSG_FILE
fi
