#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- "*.ipynb")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

# Supprimer l'output des notebook pour éviter de les commiter (peut contenir des données sensibles de fichiers de prod)
jupyter nbconvert --clear-output --inplace datacrawler/exploration-des-données/**/*.ipynb
git add "*.ipynb"
