#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- "*.ipynb")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

jupyter nbconvert --clear-output --inplace $(git diff --cached --name-only --diff-filter=ACM -- "*.ipynb" | tr "\n" " ")
