#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop test)
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)

if grep --quiet --regexp "^hel-\d\+/.*" <<< $BRANCH_NAME; then
  TICKET="${BRANCH_NAME%/*}"

  BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")

  if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]]; then
    sed -i.bak -e "1s/^/($TICKET) /" $COMMIT_MSG_FILE
  fi
else
  echo 'Le nom de branche doit correspondre à : hel-<#ticket>/<description-de-la-branche>'
  echo '(ex: hel-123/refacto-use-cases)'
  exit 1
fi
